[threat:indicator]
SHOULD_LINEMERGE = false
KV_MODE = json
INDEXED_EXTRACTIONS = json
TIME_FORMAT = %Y-%m-%d %H:%M:%S %Z
TRANSFORMS = threat_indicator_value, threat_indicator_type, threat_indicator_source, threat_indicator_confidence, threat_indicator_first_seen, threat_indicator_last_seen